version: "3"
services:
  api:
    build:
      context: .
      dockerfile: "docker/Dockerfile.api"
    volumes:
      - .:/api
    ports:
      - 1188:1188
  grpc:
    build:
      context: .
      dockerfile: "docker/Dockerfile.mikan"
    volumes:
      - .:/grpcapi
    ports:
      - 50051:50051
  nginx:
    build:
      context: .
      dockerfile: "docker/Dockerfile.nginx"
    volumes:
      - "./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro"
      - "./nginx/nginx.conf:/etc/nginx/nginx.conf:ro"
    links:
      - "api"
      - "grpc"
    ports:
      - 8080:80
      - 50055:50055
